name: Create Release ZIP

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create plugin artifact
        run: composer run-script build

      - name: Rename plugin artifact
        run:  mv zipped/remove-site-heath-from-dashboard-free.zip zipped/remove-site-heath-from-dashboard.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: zipped/remove-site-heath-from-dashboard.zip