name: Create Release ZIP

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create plugin artifact
        run: composer install -d remove-site-heath-from-dashboard --no-dev

      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        dry-run: true
        with:
            generate-zip: true
        env:
            SLUG: remove-site-heath-from-dashboard
            BUILD_DIR: ./remove-site-heath-from-dashboard
            SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
            SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.deploy.outputs.zip-path }}